# --- baseURL設定 ---
# ローカル用（必要な場合のみ切り替え）
#baseURL = 'http://localhost:1313/'

# 公開用（GitHub Pages）
#baseURL = "https://fixtan.github.io/my-blog/"
baseURL = "https://humanxai.info/"

# --- URL出力スタイル ---
relativeURLs = false       # 相対URLは使わない（← baseURLが活きる） false true
canonifyURLs = true        # 出力されるURLに baseURL を明示的に付ける
buildFuture = true         # 未来日付でも表示されるようになる

languageCode = 'ja'
title = 'lainのAIと創作ブログ'
theme = 'PaperMod'

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  author = "lain"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowShareButtons = true
  disableThemeToggle = false

[params.label]
  text = ""
  icon = ""

[params.profileMode]
  enabled = false

[params.homeInfoParams]
  disable = true
  Title = "lainのAIと創作ブログ"
  Content = "AIと創作の記録。生成AI、ブログ技術、システム開発の軌跡をまとめています。"

  [params.homeInfoParams.featured]
    enabled = true
    items = ["project1", "project2", "project3", "project4", "project5"]


[menu]
  [[menu.main]]
    identifier = "home"
    name = "ホーム"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "自己紹介"
    url = "/about/"
    weight = 2

[params.assets]
   customCSS = ["css/custom.css"]

## 記事の中でタグを有効にする
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true