[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.147.3" # あなたが使ってるHugoのバージョン（例）
  HUGO_BASEURL = "https://humanxai.info/"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200