[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.147.3" # あなたが使ってるHugoのバージョン（例）
  HUGO_BASEURL = "https://steady-malasada-321e32.netlify.app/"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200