backend:
  name: git-gateway
  repo: fixtan/my-blog
  branch: main
  site_url: "https://steady-malasada-321e32.netlify.app/"

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

# ↓ この行で JS を読み込む
local_backend: true

editor:
  preview: true

# プレビュー用 JS を読み込む
load_config_file: false

# ↓ Netlify CMS に preview script を登録
#    preview-templates.js のパスに注意！
#    ビルド後に public/admin/ に配置されてる必要あり

# Hugo の場合、次を追記
custom_script: "/admin/preview-templates.js"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" }
