backend:
  name: git-gateway
  repo: fixtan/my-blog
  branch: main
#  site_url: "https://steady-malasada-321e32.netlify.app/"
  site_url: "https://humanxai.info/"

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

# ↓ この行で JS を読み込む
local_backend: true

editor:
  preview: true

# プレビュー用 JS を読み込む
load_config_file: false

# ↓ Netlify CMS に preview script を登録
#    preview-templates.js のパスに注意！
#    ビルド後に public/admin/ に配置されてる必要あり

# Hugo の場合、次を追記
custom_script: "/admin/preview-templates.js"

collections:
  - name: "post"
    label: "記事"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "日付", name: "date", widget: "datetime" }
      - { label: "下書き", name: "draft", widget: "boolean", default: false }
      - { label: "著者", name: "author", widget: "string", default: "lain" }
      - { label: "画像", name: "image", widget: "image" }
      - { label: "概要", name: "summary", widget: "text", required: false }
      - { label: "カテゴリ", name: "categories", widget: "list", default: ["未分類"] }
      - { label: "タグ", name: "tags", widget: "list" }

      # ✅ 追加するweightフィールド
      - { label: "表示順（weight）", name: "weight", widget: "number", required: false, default: 20 }
