backend:
  name: git-gateway
  repo: fixtan/my-blog
  branch: main
  site_url: "https://steady-malasada-321e32.netlify.app/"

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

# ↓ この行で JS を読み込む
local_backend: true

editor:
  preview: true

# プレビュー用 JS を読み込む
load_config_file: false

# ↓ Netlify CMS に preview script を登録
#    preview-templates.js のパスに注意！
#    ビルド後に public/admin/ に配置されてる必要あり

# Hugo の場合、次を追記
custom_script: "/admin/preview-templates.js"

collections:
  - name: "posts"
    label: "記事"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "日付", name: "date", widget: "datetime" }
      - { label: "下書き", name: "draft", widget: "boolean", default: false }
      - { label: "著者", name: "author", widget: "string", default: "lain" }
      - { label: "アイキャッチ画像", name: "image", widget: "image", required: false }
      - { label: "概要（抜粋）", name: "summary", widget: "string", required: false, default: "（抜粋がありません）" }
      - { label: "カテゴリ", name: "categories", widget: "list", required: false, default: ["その他"] }
      - { label: "タグ", name: "tags", widget: "list", required: false }
      - { label: "本文", name: "body", widget: "markdown" }
